version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: crms-db
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "5466:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crms@123
      POSTGRES_DB: crms
    volumes:
      - postgres_data:/var/lib/postgresql/data

  crms-backend:
    build: 
      context: ./crms-backend
      dockerfile: Dockerfile
    container_name: crms-backend
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "4000:4000"
    env_file:
      - ./crms-backend/.env
    links:
      - db:db

  crms-main-frontend:
    build:
      context: ./crms-main-frontend
      dockerfile: Dockerfile
    container_name: crms-main-frontend
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "18432:80"
    links:
      - crms-backend:crms-backend
    depends_on:
      - crms-backend

volumes:
  postgres_data:
